public class CourtCasesCh4and5
{
	public static void main (String[] args)
	{
		String [][] card = {{"Dred Sccott v. Sanford", ""},
							{"Civil Rights Cases", ""},
							{"Plessy v. Ferguson", ""},
							{"Sweatt v. Painter", ""},
							{"Brown v. Board of Education", ""},
							{"Brown v. Board of Education 2", ""},
							{"Alexander v. Holmes County Board of Education", ""},
							{"Swan v. Charlotte Mecklenburg County Schools", ""},
							{"Guinn v. US", ""},
							{"Harper v. VA Board of Elections", ""},
							{"Smith v. Allwright", ""},
							{"Shaw v. Reno", ""},
							{"Santa Clara Pueblo v. Martinez", ""},
							{"Hernandez v. TX", ""},
							{"Korematsu v. US", ""},
							{"Muller v. Oregon", ""},
							{"Reed v. Reed", ""},
							{"Craig v Boren", ""},
							{"Dothard v. Rawlinson", ""},
							{"US v. VA", ""},
							{"Meritor Savings Bank v, Vinson", ""},
							{"Bowers v. Hardwick", ""},
							{"Boy Scouts of America v. Dale", ""},
							{"Lawrence v. TX", ""},
							{"Regents of the University of CA v Bakke", ""},
							{"Adarand Constructors v. Pena", ""},
							{"Grutter v. Bollinger", ""},
							{"Gratz v. Bollinger", ""},
							{"Barron v. Baltimore", ""},
							{"Schenck v. US", ""},
							{"Gitlow v. NY", ""},
							{"Lemon v. Kurtzman", ""},
							{"Everson v Board of Ed.", ""},
							{"Engles v. Vitale", ""},
							{"Wisconson v. Yoder", ""},
							{"Reynold v. US", ""},
							{"Lukumi Babalu Aye, Inc. v City of Hialeah", ""},
							{"Near v Minnesota", ""},
							{"Hazelwood v. Kuhlmeier", ""},
							{"Dennis v. US", ""},
							{"Yates v US", ""},
							{"Brandenburg v. OH", ""},
							{"Roth v US", ""},
							{"Miller v CA", ""},
							{"NY Times v Sullivan", ""},
							{"Hustler Magazine v Falwell", ""},
							{"Tinker v Des Moines", ""},
							{"TX v Johnson", ""},
							{"US v O'Brien", ""},
							{"Buckley v Valeo", ""},
							{"Citizens United v Federal Elections Commission", ""},
							{"Snyder v Phelps", ""},
							{"DC v Heller", ""},
							{"McDonald v Chicago", ""},
							{"Kyllo v US", ""},
							{"Terry v OH", ""},
							{"NJ v T.L.O.", ""},
							{"AZ v Gant", ""},
							{"US v Jones", ""},
							{"Weeks v US", ""},
							{"Mapp v OH", ""},
							{"Nix v Williams", ""},
							{"Miranda v AZ", ""},
							{"Powell v AL", ""},
							{"Betts v Brady", ""},
							{"Gideon v Wainwright", ""},
							{"Hamdam v Rumsfeld", ""},
							{"Boumediene v Bush", ""},
							{"Furman v GA", ""},
							{"Woodson v NC", ""},
							{"Gregg v GA", ""},
							{"McKlesky v Kemp", ""},
							{"Atkins v VA", ""},
							{"Roper v Simmons", ""},
							{"Coker v GA", ""},
							{"Griswold v CT", ""},
							{"Roe v Wade", ""},
							{"Planned Parenthood v Casey", ""},
							{"NAACP v AL",""}};

		FlashCards gov = new FlashCards (card);
		gov.learn ();
	}
}